<template>
  <select
    class="u-input"
    v-model="$store.state.colorSpace"
    @change="$store.commit('updateLayerName')"
  >
    <option>rgb</option>
    <option>hsl</option>
    <option>lab</option>
    <option>lch</option>
    <option>lrgb</option>
  </select>
</template>
